### ISSUE TITLE
Docker container won't start

### ISSUE THREAD

**Issue by alexjeen** [alexjeen/docker-stack#4]
Should be able to compose when coming "fresh out of the box":

![image](https://user-images.githubusercontent.com/1567497/55293920-09a23480-53fc-11e9-9001-933cf7a9297e.png)

I saw the database paths are being created automatically, but it's not clear where the webfolder should be. There should be placeholder files in there or a .gitkeep.

(also include this in README)

**Comment by alexjeen** [comment]
Also check the commands in databrydge_aws. They seem to be wrong (don't work on execute).

**Comment by Melvin-de-Jong** [comment]
Locations are now created with a gitignore in ./data, console container allows for executing all commands
